---
title: "vaibhav_EDA"
author: "Vaibhav Jha"
date: "2026-04-05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read in data
```{r}
df <- read.csv('/Users/vaibhavjha/Documents/Time Series/Project/Monthly_Modal_Time_Series.csv')
head(df)
```

Filter for Pittsburgh Regional Transit, bus system ('Motor Bus')
```{r}
burgh.df <- df[df$Agency == 'Pittsburgh Regional Transit', ]
table(burgh.df$Mode)

burgh.bus.df <- burgh.df[burgh.df$Mode == 'MB', ]
burgh.bus.df
```

Filter for 2021-2025
```{r}
burgh.bus.df <- burgh.bus.df[burgh.bus.df$Year >= 2021 & burgh.bus.df$Year <= 2025, ]
burgh.bus.df
nrow(burgh.bus.df)
```

Select columns of interest:
```{r}
final.df <- burgh.bus.df[, c('Year', 'Month', 'Unlinked.Passenger.Trips'), ]
rownames(final.df) <- NULL
final.df
```

Transform data into TS object
```{r}
ts.df <- ts(final.df$Unlinked.Passenger.Trips,
            start = c(2021, 1),
            end = c(2025, 12),
            frequency = 12)
```

Plots
```{r}
par(mgp = c(3, 1, 0))
plot(ts.df,
     lwd = 2,
     xlab = "Year",
     ylab = "Ridership",
     main = "Pittsburgh Regional Transit from 2021-2026",
     sub = "Measured in millions of riders (M)",
     type = "l",
     col = 'steelblue',
     yaxt = "n")
axis(2, 
     at = axTicks(2), 
     labels = paste0(axTicks(2)/1e6, "M"),
     las = 2)
```

ACF/PACF
```{r}
acf(ts.df)
pacf(ts.df)
```

